services:
  postgres:
    image: postgres:16
    container_name: nt-media-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nt_media
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
